CREATE TABLE `controle_pedidos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`data` timestamp NOT NULL,
	`cliente` varchar(255) NOT NULL,
	`telefone` varchar(50),
	`item` varchar(500) NOT NULL,
	`quantidade` varchar(255),
	`tipoImpressao` varchar(100),
	`propriaTerceirizada` enum('Própria','Terceirizada') DEFAULT 'Própria',
	`insumo1` varchar(255),
	`insumo2` varchar(255),
	`insumo3` varchar(255),
	`materialTeste` varchar(255),
	`previsaoEntrega` timestamp,
	`valorNegociado` decimal(10,2),
	`formaPagamento` varchar(100),
	`sinal` decimal(10,2) DEFAULT '0.00',
	`valorFinal` decimal(10,2),
	`dataPagamento` timestamp,
	`observacoesFinais` text,
	`statusControle` enum('pendente','em_producao','finalizado','entregue','cancelado') DEFAULT 'pendente',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `controle_pedidos_id` PRIMARY KEY(`id`)
);
